import terrain from '~/map/terrain.png';
import singleBarrelCannon from '~/towers/singleBarrelCannon.png';
import doubleBarrelCannon from '~/towers/doubleBarrelCannon.png';
import doubleBarrelCannonPlus from '~/towers/doubleBarrelCannonPlus.png';
import tripleBarrelCannon from '~/towers/tripleBarrelCannon.png';
import simpleLaserCannon from '~/towers/simpleLaserCannon.png';
import advancedLaserCannon from '~/towers/advancedLaserCannon.png';
import supremeLaserCannon from '~/towers/supremeLaserCannon.png';
import supremeLaserCannonPlus from '~/towers/supremeLaserCannonPlus.png';
import platform from '~/platforms/platforms-no-background.png';
import smallDragonMove from '~/monsters/smallDragon/smallDragonMove.png';
import medusaMove from '~/monsters/medusa/medusaMove.png'
import dragonMove from '~/monsters/dragon/dragonMove.png'
import demonMove from '~/monsters/demon/demonMove.png'
import jinnMove from '~/monsters/jinn/jinnMove.png'
import lizardMove from '~/monsters/lizard/lizardMove.png'
import demonBoss from '~/monsters/demonBoss/demonBoss.png'
import smallExplosion from '~/towers/explosion/smallExplosion_9_111x109.png'
import energy from '~/towers/explosion/energy_11_63x83.png'
import plasma from '~/towers/explosion/plasma_4_526x526.png'
import blueRing from '~/towers/explosion/blueRing_18_200x200.png'
import bigFireExplosion from '~/towers/explosion/bigFireExplosion.png'
import bigRingExplosion from '~/towers/explosion/bigRingExplosion20_128_128.png'
import hugeExplosion from '~/towers/explosion/boom_20_128x128.png'


export class ImagePath {
	static terrain = terrain;
	static singleBarrelCannon = singleBarrelCannon;
	static doubleBarrelCannon = doubleBarrelCannon;
	static tripleBarrelCannon = tripleBarrelCannon;
	static simpleLaserCannon = simpleLaserCannon;
	static advancedLaserCannon = advancedLaserCannon;
	static supremeLaserCannon = supremeLaserCannon;
	static supremeLaserCannonPlus = supremeLaserCannonPlus;
	static doubleBarrelCannonPlus = doubleBarrelCannonPlus;
	static platform = platform;
	static demonMove = demonMove;
	static smallDragonMove = smallDragonMove;
	static demonBoss = demonBoss;
	static medusaMove = medusaMove;
	static dragonMove = dragonMove;
	static jinnMove = jinnMove;
	static lizardMove = lizardMove;
	static smallExplosion = smallExplosion;
	static energy = energy;
	static plasma = plasma;
	static blueRing = blueRing;
	static bigFireExplosion = bigFireExplosion;
	static bigRingExplosion33 = bigRingExplosion;
	static hugeExplosion = hugeExplosion;
}
