import terrain from '~/map/terrain.png';
import singleBarrelCannon from '~/towers/singleBarrelCannon.png';
import doubleBarrelCannon from '~/towers/doubleBarrelCannon.png';
import doubleBarrelCannonPlus from '~/towers/doubleBarrelCannonPlus.png';
import tripleBarrelCannon from '~/towers/tripleBarrelCannon.png';
import simpleLaserCannon from '~/towers/simpleLaserCannon.png';
import advancedLaserCannon from '~/towers/advancedLaserCannon.png';
import supremeLaserCannon from '~/towers/supremeLaserCannon.png';
import supremeLaserCannonPlus from '~/towers/supremeLaserCannonPlus.png';
import platform from '~/platforms/platforms-no-background.png';
import smallDragonMove from '~/monsters/smallDragon/smallDragonMove.png';
import medusaMove from '~/monsters/medusa/medusaMove.png'
import dragonMove from '~/monsters/dragon/dragonMove.png'
import demonMove from '~/monsters/demon/demonMove.png'
import jinnMove from '~/monsters/jinn/jinnMove.png'
import lizardMove from '~/monsters/lizard/lizardMove.png'
import demonBoss from '~/monsters/demonBoss/demonBoss.png'
import bigExplosion from '~/towers/explosion/explosionBig.png'


export class ImagePath {
	static terrain = terrain;
	static singleBarrelCannon = singleBarrelCannon;
	static doubleBarrelCannon = doubleBarrelCannon;
	static tripleBarrelCannon = tripleBarrelCannon;
	static simpleLaserCannon = simpleLaserCannon;
	static advancedLaserCannon = advancedLaserCannon;
	static supremeLaserCannon = supremeLaserCannon;
	static supremeLaserCannonPlus = supremeLaserCannonPlus;
	static doubleBarrelCannonPlus = doubleBarrelCannonPlus;
	static platform = platform;
	static demonMove = demonMove;
	static smallDragonMove = smallDragonMove;
	static demonBoss = demonBoss;
	static medusaMove = medusaMove;
	static dragonMove = dragonMove;
	static jinnMove = jinnMove;
	static lizardMove = lizardMove;
	static bigExplosion = bigExplosion;
}
